name: Check Linting
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm ci
      - name: Lint Check
        run: npm run lint
