name: Check Linting
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: node -v
      - run: npm -v
      - name: Install Packages
        run: npm i
      - name: Lint Check
        run: npm run lint
